# DX 602 Final Project

## Introduction

In this project, you will practice the skills that you have learned throughout this module with a heavy focus on building models.
Most of the problems and questions are open ended compared to your previous homeworks, and you will be asked to explain your choices.
Most of them will have a particular type of solution implied, but it is up to you to figure out the details based on what you have learned in this module.

## Instructions

Each problem asks you to perform build models, run a computation, or otherwise perform some analysis of the data, and usually answer some questions about the results.
Make sure that your question answers are well supported by your analysis and explanations; simply stating an answer without support will earn minimal points.

Notebook cells for code and text have been added for your convenience, but feel free to add additional cells.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Submission

This project will be entirely manually graded.
However, we may rerun some or all of your code to confirm that it works as described.

### Late Policy

The normal homework late policy for OMDS does not apply to this project.
Boston University requires final grades to be submitted within 72 hours of class instruction ending, so we cannot accommodate 5 days of late submissions.

However, we have delayed the due date of this project to be substantially later than necessary given its scope, and given you more days for submission with full credit than you would have had days for submission with partial credit under the homework late policy.
The Thanksgiving holiday was also taken into account in setting the deadline.
Finally, the deadlines for DX 601 and DX 602 were coordinated to be a week apart while giving ample time for both of their projects.

## Shared Imports

For this project, you are forbidden to use modules that were not loaded in this template.
While other modules are handy in practice, modules that trivialize these problems interfere with our assessment of your own knowledge and skills.

If you believe a module covered in the course material (not live sessions) is missing, please check with your learning facilitator.

In [1]:
import math
import sys

In [6]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats
import sklearn.linear_model

## Problems

### Problem 1 (5 points)

Pick one of the following data sets to analyze in this project.
Load the data set, and show a random sample of 10 rows.

* [Wine Quality](https://archive.ics.uci.edu/dataset/186/wine+quality) ([PMLB - red subset only](https://github.com/EpistasisLab/pmlb/tree/master/datasets/wine_quality_red))
* [Body Fat](https://www.openml.org/search?type=data&status=active&id=560) ([PMLB](https://github.com/EpistasisLab/pmlb/tree/master/datasets/560_bodyfat))

The PMLB copies of the data are generally cleaner and recommended for this project, but the other links are provided to give you more context.
To load the data from the PMLB Github repository, navigate to the `.tsv.gz` file in GitHub and copy the link from the "Raw" button.

If the dataset has missing data, you should drop the rows with missing data before proceeding.
If the data set you choose has more than ten columns, you may limit later analysis that is requested per column to just the first ten columns.

In [43]:
# Load the Dataset

body_fat = pd.read_csv("https://github.com/EpistasisLab/pmlb/raw/refs/heads/master/datasets/560_bodyfat/560_bodyfat.tsv.gz",sep="\t")

In [ ]:
# Check the shape of the Dataset

body_fat.shape

(252, 15)

In [ ]:
# Show a random sample of 10 rows in the Dataset

body_fat.sample(10)

,Density,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist,target
175,1.0763,37.0,145.25,69.25,36.000000,96.800003,79.400002,89.199997,50.299999,34.799999,22.200001,31.000000,26.900000,16.900000,9.900000
188,1.0520,41.0,202.25,72.50,40.799999,109.199997,98.000000,101.800003,62.799999,41.299999,24.799999,36.599998,32.400002,18.799999,20.500000
151,1.0542,26.0,241.75,74.50,41.799999,108.300003,102.900002,114.400002,72.900002,43.500000,25.100000,38.500000,33.799999,19.600000,19.600000
10,1.0830,26.0,186.25,74.50,38.500000,101.500000,83.599998,98.199997,59.700001,39.700001,25.200001,32.799999,29.400000,18.500000,7.100000
39,1.0258,50.0,203.00,67.00,40.200001,114.800003,108.099998,102.500000,61.299999,41.099998,24.700001,34.099998,31.000000,18.299999,32.599998
20,1.0551,28.0,179.00,68.00,39.099998,103.300003,95.900002,104.900002,63.500000,38.000000,22.100000,32.500000,30.299999,18.400000,19.100000
202,1.0340,43.0,200.50,71.50,37.900002,107.199997,103.099998,105.500000,68.800003,38.299999,23.700001,32.099998,28.900000,18.700001,28.700001
43,1.0269,41.0,212.00,71.50,41.500000,106.599998,104.300003,106.000000,65.000000,40.200001,23.000000,35.799999,31.500000,18.799999,32.000000
128,1.0515,40.0,192.25,73.25,39.799999,103.900002,93.500000,99.500000,61.700001,39.000000,21.799999,33.299999,29.600000,18.100000,20.799999
157,1.0761,28.0,182.50,72.25,37.000000,98.500000,90.800003,102.500000,60.799999,38.500000,25.000000,31.600000,28.000000,18.600000,10.000000

In [ ]:
# Drop rows with missing data

body_fat = body_fat.dropna()

In [ ]:
# Check the shape of the dataframe again

body_fat.shape

(252, 15)

In [47]:
# Set the dataframe to just 10 columns

body_fat = body_fat[["Density", "Age", "Weight", "Height", "Neck", "Chest", "Abdomen", "Hip", "Thigh", "target"]]

In [48]:
# Check the shape of the dataframe again to endure 10 columns

body_fat.shape

(252, 10)

In [50]:
# Show a random sample of 10 rows, with just the 10 columns

body_fat.sample(10)

,Density,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,target
55,1.0473,54.0,198.00,72.00,39.900002,107.599998,100.000000,99.599998,57.200001,22.600000
159,1.0477,31.0,177.25,71.50,36.200001,101.099998,92.400002,99.300003,59.400002,22.500000
194,1.0470,42.0,162.75,72.75,35.400002,92.199997,85.599998,96.500000,60.200001,22.799999
214,1.0543,50.0,172.75,73.00,37.400002,98.699997,87.599998,96.099998,57.099998,19.500000
117,1.0671,51.0,179.00,72.00,41.000000,99.199997,90.000000,96.400002,56.799999,13.900000
69,1.0693,55.0,156.75,71.50,36.299999,94.400002,84.599998,94.300003,51.200001,12.900000
160,1.0775,31.0,151.25,72.25,35.000000,94.000000,81.199997,91.500000,52.500000,9.400000
53,1.0848,49.0,152.75,73.50,35.099998,93.300003,79.599998,91.599998,52.599998,6.300000
52,1.0807,51.0,137.25,67.75,36.500000,89.699997,82.000000,89.099998,49.299999,8.000000
193,1.0429,42.0,224.75,74.75,38.500000,106.699997,105.699997,111.800003,65.300003,24.700001

YOUR ANSWERS HERE

### Problem 2 (10 points)

List all of the columns and describe them in your own words.

In [49]:
# YOUR CODE HERE: List all of the columns
body_fat.columns

Index(['Density', 'Age', 'Weight', 'Height', 'Neck', 'Chest', 'Abdomen', 'Hip',
       'Thigh', 'target'],
      dtype='object')

### Describe the Columns:
* Density: Body Density of the men being studied, measured in (gm/cm^3)
* Age: the age of the men being studied, measured in (years)
* Weight: the weight of the men being studied, measured in (lbs)
* Height: height of the men being studied, measured in (inches)
* Neck: circumference measurement of the neck of the men being studied, measured in (cm)
* Chest: circumference measurement of the chest of the men being studied, measured in (cm)
* Abdomen: circumference measurement of the abdomen of the men being studied, measured in (cm)
* Hip: circumference measurement of the hip of the men being studied, measured in (cm)
* Thigh: circumference measurement of the thigh of the men being studied, measured in (cm)
* target: the percentage of body fat determined by underwater weighing

YOUR ANSWERS HERE

### Problem 3 (50 points)

Perform an exploratory analysis of the data set.
After your exploratory analysis, pick 3 individual charts that you the think were particularly interesting.
Repeat those charts separately from your original analysis, and after each of those charts, explain what you thought was noteworthy.

In [ ]:
# YOUR CODE HERE

YOUR ANSWERS HERE

### Problem 4 (5 points)

Plot the correlation matrix of the numeric columns in the data set.
Which pair of different columns were highlighted as the most correlated?

In [ ]:
# YOUR CODE HERE

YOUR ANSWERS HERE

### Problem 5 (10 points)

Pick three different regression model classes to try in problem 6 from the scikit-learn documentation.
For each class, provide a link to the scikit-learn documentation, and a link to another web page describing how that kind of model works.
The second link should not be from scikit-learn, but Wikipedia is acceptable.
You do not need to understand the methods at this time, but it is good to be comfortable researching them.

In [ ]:
# YOUR CODE HERE

YOUR ANSWERS HERE

### Problem 6 (50 points)

Build three different regression models using the entire data set.
Plot the actual target vs the predicted values for each in one chart.
Compute the L2 and L1 losses for each of them.
You may use any regression class provided provided by scikit-learn, and you may reuse one class as long as you change its parameters enough to see different results.

In [ ]:
# YOUR CODE HERE

YOUR ANSWERS HERE

### Problem 7 (30 points)

Use 5-fold cross-validation to repeat building the same three kinds of regression models. Compare the L2 losses predicted by cross-validation against the L2 losses training against the whole data set. (The difference is likely from overfitting in the latter.)

In [ ]:
# YOUR CODE HERE

YOUR ANSWERS HERE

### Problem 8 (25 points)

Build three different regression models as in problem 6, but preprocess the data so that each column has mean zero and standard deviation one first.
For full credit, use a scikit-learn pipeline for each model.
For each model, compare the L2 losses -- which of them performed differently from your results in problem 6?

(This process will be covered in week 13.)

In [ ]:
# YOUR CODE HERE

YOUR ANSWERS HERE

### Problem 9 (5 points)

A colleague suggests that you find better models by repeatedly building decision trees with random depth limits.
They say that trying 1000 such models will likely find an improvement as long as you use cross validation.
Give a one sentence response to this suggestion.

In [ ]:
# YOUR CODE HERE

YOUR ANSWERS HERE

### Problem 10 (10 points)

Pick a best model from all the models that you built and otherwise described in this project.
Explain how you picked it, including what criteria you chose, and how the other models compared by that criteria.
As much as possible, justify that problem in the context of the original data set.

In [ ]:
# YOUR CODE HERE

YOUR ANSWERS HERE